import { StyleSheet } from 'react-native';
import { ThemeColors } from '@/shared/styles/theme';

export const getStyles = (c: ThemeColors) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: c.background,
    },
    container: {
      flex: 1,
      backgroundColor: c.background,
    },
    contentContainer: {
      padding: 14,
      paddingBottom: 28,
      gap: 12,
    },
    emptyState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.background,
    },
    emptyText: {
      color: c.text,
      fontSize: 16,
    },

    headerCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
      borderColor: c.border,
      elevation: 2,
    },
    headerTop: {
      flexDirection: 'row',
      gap: 10,
    },
    characterPhoto: {
      width: 74,
      height: 74,
      borderRadius: 37,
    },
    placeholderPhoto: {
      width: 74,
      height: 74,
      borderRadius: 37,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.inputBackground,
    },
    headerInfo: {
      flex: 1,
      justifyContent: 'center',
      gap: 4,
    },
    nameRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    characterName: {
      color: c.text,
      fontSize: 22,
      fontWeight: '700',
      maxWidth: '86%',
    },
    characterMeta: {
      color: c.textSecondary,
      fontSize: 13,
    },
    badgesRow: {
      flexDirection: 'row',
      gap: 6,
      flexWrap: 'wrap',
      marginTop: 2,
    },
    badge: {
      borderRadius: 99,
      paddingVertical: 4,
      paddingHorizontal: 8,
      backgroundColor: c.inputBackground,
    },
    badgeSuccess: {
      backgroundColor: '#2f8f46',
    },
    badgeWarning: {
      backgroundColor: '#b2751a',
    },
    badgeAccent: {
      backgroundColor: '#2f95dc',
    },
    badgeDanger: {
      backgroundColor: '#8b1e1e',
    },
    badgeText: {
      color: c.text,
      fontSize: 11,
      fontWeight: '600',
    },
    badgeTextInverted: {
      color: '#fff',
    },
    syncIndicatorRow: {
      marginTop: 4,
      gap: 2,
    },
    syncIndicatorText: {
      color: c.textSecondary,
      fontSize: 11,
    },
    syncNowButton: {
      marginTop: 6,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 8,
      paddingHorizontal: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      alignSelf: 'flex-start',
    },
    syncNowButtonText: {
      color: c.text,
      fontSize: 12,
      fontWeight: '700',
    },

    modeRow: {
      marginTop: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    modeSwitch: {
      flex: 1,
      flexDirection: 'row',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: 2,
      gap: 2,
    },
    modeButton: {
      flex: 1,
      borderRadius: 10,
      minHeight: 42,
      paddingVertical: 9,
      paddingHorizontal: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
    },
    modeButtonActive: {
      backgroundColor: c.text,
    },
    modeButtonText: {
      color: c.text,
      fontWeight: '700',
      fontSize: 13,
      textAlign: 'center',
      width: '100%',
      flexShrink: 1,
      includeFontPadding: false,
    },
    modeButtonTextActive: {
      color: c.background,
    },
    sessionToggle: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 9,
      paddingHorizontal: 10,
    },
    sessionToggleActive: {
      backgroundColor: '#2f95dc',
      borderColor: '#2f95dc',
    },
    sessionToggleText: {
      color: c.text,
      fontSize: 12,
      fontWeight: '700',
    },
    sessionToggleTextActive: {
      color: '#fff',
    },
    sessionModeNote: {
      marginTop: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 8,
      paddingHorizontal: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    sessionModeNoteActive: {
      backgroundColor: '#d1e7dd',
      borderColor: '#198754',
    },
    sessionModeNoteText: {
      color: c.textSecondary,
      fontSize: 12,
      flex: 1,
    },
    sessionModeNoteTextActive: {
      color: '#0f5132',
      fontWeight: '600',
    },

    conflictCard: {
      backgroundColor: c.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#f59e0b',
      padding: 12,
      elevation: 2,
      gap: 8,
    },
    conflictHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    conflictTitle: {
      color: c.text,
      fontSize: 14,
      fontWeight: '700',
    },
    conflictText: {
      color: c.textSecondary,
      fontSize: 12,
      lineHeight: 18,
    },
    conflictPaths: {
      color: c.text,
      fontSize: 12,
      fontWeight: '600',
    },
    conflictActionsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    conflictAction: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 9,
      paddingHorizontal: 10,
      minWidth: 94,
      alignItems: 'center',
    },
    conflictActionText: {
      color: c.text,
      fontSize: 12,
      fontWeight: '700',
    },

    combatSummaryCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
      borderColor: c.border,
      elevation: 2,
    },
    summaryTitle: {
      color: c.text,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 10,
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    summaryTileWide: {
      width: '100%',
      backgroundColor: c.background,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      padding: 10,
      marginBottom: 2,
    },
    summaryTile: {
      width: '31%',
      minWidth: 92,
      backgroundColor: c.background,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      padding: 10,
    },
    summaryLabel: {
      color: c.textSecondary,
      fontSize: 11,
      marginBottom: 4,
    },
    summaryValue: {
      color: c.text,
      fontSize: 18,
      fontWeight: '700',
    },
    summarySubValue: {
      color: c.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    hpBarBase: {
      marginTop: 8,
      height: 7,
      borderRadius: 999,
      backgroundColor: c.inputBackground,
      overflow: 'hidden',
    },
    hpBarFill: {
      height: '100%',
      backgroundColor: '#e63946',
      borderRadius: 999,
    },

    quickActionsWrapper: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
      borderColor: c.border,
      elevation: 2,
    },
    quickActionsRow: {
      gap: 8,
      paddingRight: 6,
    },
    quickActionButton: {
      minWidth: 84,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 10,
      paddingHorizontal: 8,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      elevation: 1,
    },
    quickActionText: {
      color: c.text,
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'center',
    },

    tabsWrap: {
      borderRadius: 14,
      paddingVertical: 6,
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.border,
      elevation: 1,
    },
    tabsRow: {
      gap: 8,
      paddingHorizontal: 8,
    },
    tabChip: {
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 8,
      backgroundColor: c.background,
      borderWidth: 1,
      borderColor: c.border,
    },
    tabChipInner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    tabChipActive: {
      backgroundColor: c.text,
      borderColor: c.text,
    },
    tabChipConflict: {
      borderColor: '#f59e0b',
    },
    tabChipText: {
      color: c.text,
      fontSize: 12,
      fontWeight: '700',
    },
    tabChipTextActive: {
      color: c.background,
    },

    tabContent: {
      gap: 10,
    },
    historyRow: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: 9,
      gap: 3,
    },
    historyAuthor: {
      color: c.text,
      fontSize: 12,
      fontWeight: '700',
    },
    historyMeta: {
      color: c.textSecondary,
      fontSize: 11,
    },
    historyPaths: {
      color: c.text,
      fontSize: 11,
      lineHeight: 16,
    },
    cardPrimary: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
      borderColor: c.border,
      elevation: 2,
    },
    cardSecondary: {
      backgroundColor: c.card,
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
      borderColor: c.border,
      elevation: 2,
      gap: 6,
    },
    cardHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    sectionTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
      flex: 1,
    },
    sectionTitle: {
      color: c.text,
      fontSize: 15,
      fontWeight: '700',
    },
    sectionConflictBadge: {
      borderRadius: 99,
      borderWidth: 1,
      borderColor: '#f59e0b',
      backgroundColor: '#3f2f0f',
      paddingVertical: 2,
      paddingHorizontal: 8,
    },
    sectionConflictBadgeText: {
      color: '#fbbf24',
      fontSize: 10,
      fontWeight: '700',
    },
    subSectionTitle: {
      color: c.text,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 6,
    },
    collapseButton: {
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 6,
      backgroundColor: c.background,
      borderWidth: 1,
      borderColor: c.border,
    },
    collapseButtonText: {
      color: c.text,
      fontSize: 12,
      fontWeight: '600',
    },

    statGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 8,
    },
    statTile: {
      width: '31%',
      minWidth: 92,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 9,
      paddingHorizontal: 10,
      alignItems: 'center',
    },
    statName: {
      color: c.textSecondary,
      fontSize: 11,
    },
    statScore: {
      color: c.text,
      fontSize: 20,
      fontWeight: '700',
      marginTop: 4,
    },
    statMod: {
      color: c.text,
      fontSize: 12,
      marginTop: 2,
      fontWeight: '600',
    },

    rowLine: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      paddingVertical: 7,
      gap: 8,
    },
    rowLabel: {
      color: c.text,
      fontSize: 13,
      flex: 1,
    },
    rowValue: {
      color: c.text,
      fontSize: 13,
      fontWeight: '600',
      maxWidth: '55%',
      textAlign: 'right',
    },
    weaponCombatCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: 8,
      gap: 8,
    },
    weaponActionRow: {
      flexDirection: 'row',
      gap: 8,
    },
    weaponActionButton: {
      flex: 1,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      paddingVertical: 9,
      paddingHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    weaponActionButtonPrimary: {
      backgroundColor: '#255ddf',
      borderColor: '#255ddf',
    },
    weaponActionButtonSecondary: {
      backgroundColor: '#7a3e16',
      borderColor: '#7a3e16',
    },
    weaponActionText: {
      color: '#fff',
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'center',
    },
    weaponRollResultLine: {
      color: c.text,
      fontSize: 13,
      lineHeight: 18,
    },
    blockText: {
      color: c.text,
      fontSize: 13,
      lineHeight: 19,
    },
    blockTextMuted: {
      color: c.textSecondary,
      fontSize: 12,
    },
    conditionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 3,
    },
    conditionText: {
      color: c.text,
      fontSize: 13,
      flex: 1,
    },

    trackerCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: 10,
      gap: 8,
    },
    trackerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    trackerName: {
      color: c.text,
      fontSize: 14,
      fontWeight: '700',
    },
    trackerMeta: {
      color: c.textSecondary,
      fontSize: 12,
    },
    trackerControls: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 12,
    },
    quickCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: c.inputBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickCircleText: {
      color: c.text,
      fontSize: 20,
      fontWeight: '700',
      marginTop: -1,
    },
    trackerValue: {
      color: c.text,
      fontSize: 18,
      fontWeight: '700',
      minWidth: 78,
      textAlign: 'center',
    },

    editLabel: {
      color: c.textSecondary,
      fontSize: 12,
      marginTop: 8,
    },
    editInput: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      color: c.text,
      paddingHorizontal: 10,
      paddingVertical: 9,
      fontSize: 14,
    },
    editInputMultiline: {
      minHeight: 92,
      textAlignVertical: 'top',
    },
    slotEditRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 6,
    },
    slotInput: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      color: c.text,
      paddingHorizontal: 10,
      paddingVertical: 8,
      width: 72,
      textAlign: 'center',
    },
    secondaryAction: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 9,
      alignItems: 'center',
      marginTop: 6,
    },
    secondaryActionText: {
      color: c.text,
      fontSize: 13,
      fontWeight: '700',
    },
    editCardBlock: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: 10,
      marginTop: 8,
      gap: 4,
    },
    booleanField: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      paddingVertical: 10,
      alignItems: 'center',
      marginTop: 4,
    },
    removeButton: {
      borderRadius: 10,
      backgroundColor: '#7f1d1d',
      paddingVertical: 8,
      alignItems: 'center',
      marginTop: 8,
    },
    removeButtonText: {
      color: '#fff',
      fontSize: 12,
      fontWeight: '700',
    },

    modalLabel: {
      color: c.text,
      marginBottom: 6,
      marginTop: 4,
    },
    modalInput: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      color: c.text,
      paddingHorizontal: 10,
      paddingVertical: 9,
      marginBottom: 8,
    },
    modalInputMultiline: {
      minHeight: 88,
      textAlignVertical: 'top',
    },
    restButton: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 10,
      alignItems: 'center',
      marginBottom: 8,
    },
    restButtonText: {
      color: c.text,
      fontWeight: '700',
    },
  });
