import { StyleSheet } from 'react-native';
import { ThemeColors } from '@/shared/styles/theme';
import { fs, rd, sp } from '@/shared/styles/tokens';

export const getStyles = (c: ThemeColors) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: c.background,
    },
    container: {
      flex: 1,
      backgroundColor: c.background,
    },
    contentContainer: {
      padding: sp(10),
      paddingBottom: 28,
      gap: sp(10),
    },
    emptyState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.background,
    },
    emptyText: {
      color: c.text,
      fontSize: fs(16),
    },

    headerCard: {
      backgroundColor: c.card,
      borderRadius: rd(12),
      padding: sp(10),
      borderWidth: 1,
      borderColor: c.border,
      elevation: 2,
    },
    headerTop: {
      flexDirection: 'row',
      gap: sp(8),
    },
    characterPhoto: {
      width: 58,
      height: 58,
      borderRadius: rd(29),
    },
    placeholderPhoto: {
      width: 58,
      height: 58,
      borderRadius: rd(29),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.inputBackground,
    },
    headerInfo: {
      flex: 1,
      justifyContent: 'center',
      gap: sp(4),
    },
    nameRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    characterName: {
      color: c.text,
      fontSize: fs(19),
      fontWeight: '700',
      maxWidth: '86%',
    },
    characterMeta: {
      color: c.textSecondary,
      fontSize: fs(13),
    },
    badgesRow: {
      flexDirection: 'row',
      gap: sp(6),
      flexWrap: 'wrap',
      marginTop: sp(2),
    },
    badge: {
      borderRadius: rd(99),
      paddingVertical: sp(4),
      paddingHorizontal: sp(8),
      backgroundColor: c.inputBackground,
    },
    badgeSuccess: {
      backgroundColor: c.success,
    },
    badgeWarning: {
      backgroundColor: c.warning,
    },
    badgeAccent: {
      backgroundColor: c.primary,
    },
    badgeDanger: {
      backgroundColor: c.danger,
    },
    badgeText: {
      color: c.text,
      fontSize: fs(11),
      fontWeight: '600',
    },
    badgeTextInverted: {
      color: c.onPrimary,
    },
    syncIndicatorRow: {
      marginTop: sp(4),
      gap: sp(2),
    },
    syncIndicatorText: {
      color: c.textSecondary,
      fontSize: fs(11),
    },
    syncNowButton: {
      marginTop: sp(6),
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(8),
      paddingHorizontal: sp(10),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: sp(6),
      alignSelf: 'flex-start',
    },
    syncNowButtonText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '700',
    },

    modeRow: {
      marginTop: sp(8),
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(8),
    },
    modeSwitch: {
      flex: 1,
      flexDirection: 'row',
      borderRadius: rd(12),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: sp(2),
      gap: sp(2),
    },
    modeButton: {
      flex: 1,
      borderRadius: rd(10),
      minHeight: 38,
      paddingVertical: sp(7),
      paddingHorizontal: sp(8),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
    },
    modeButtonActive: {
      backgroundColor: c.text,
    },
    modeButtonText: {
      color: c.text,
      fontWeight: '700',
      fontSize: fs(13),
      textAlign: 'center',
      width: '100%',
      flexShrink: 1,
      includeFontPadding: false,
    },
    modeButtonTextActive: {
      color: c.background,
    },
    sessionToggle: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(7),
      paddingHorizontal: sp(10),
    },
    sessionToggleActive: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    sessionToggleText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '700',
    },
    sessionToggleTextActive: {
      color: c.onPrimary,
    },
    sessionModeNote: {
      marginTop: sp(8),
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(8),
      paddingHorizontal: sp(10),
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(8),
    },
    sessionModeNoteActive: {
      backgroundColor: c.success,
      borderColor: c.success,
    },
    sessionModeNoteText: {
      color: c.textSecondary,
      fontSize: fs(12),
      flex: 1,
    },
    sessionModeNoteTextActive: {
      color: c.onSuccess,
      fontWeight: '600',
    },

    conflictCard: {
      backgroundColor: c.card,
      borderRadius: rd(14),
      borderWidth: 1,
      borderColor: c.warning,
      padding: sp(12),
      elevation: 2,
      gap: sp(8),
    },
    conflictHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(8),
    },
    conflictTitle: {
      color: c.text,
      fontSize: fs(14),
      fontWeight: '700',
    },
    conflictText: {
      color: c.textSecondary,
      fontSize: fs(12),
      lineHeight: 18,
    },
    conflictPaths: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '600',
    },
    conflictActionsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(8),
    },
    conflictAction: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(9),
      paddingHorizontal: sp(10),
      minWidth: 94,
      alignItems: 'center',
    },
    conflictActionText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '700',
    },

    combatSummaryCard: {
      backgroundColor: c.card,
      borderRadius: rd(12),
      padding: sp(10),
      borderWidth: 1,
      borderColor: c.border,
      elevation: 2,
    },
    summaryTitle: {
      color: c.text,
      fontSize: fs(15),
      fontWeight: '700',
      marginBottom: sp(6),
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(6),
    },
    summaryTileWide: {
      width: '48%',
      backgroundColor: c.background,
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      padding: sp(8),
      marginBottom: sp(2),
    },
    summaryTile: {
      width: '23%',
      minWidth: 76,
      backgroundColor: c.background,
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      padding: sp(8),
    },
    summaryLabel: {
      color: c.textSecondary,
      fontSize: fs(11),
      marginBottom: sp(4),
    },
    summaryValue: {
      color: c.text,
      fontSize: fs(16),
      fontWeight: '700',
    },
    summarySubValue: {
      color: c.textSecondary,
      fontSize: fs(12),
      marginTop: sp(2),
    },
    hpBarBase: {
      marginTop: sp(8),
      height: 7,
      borderRadius: rd(999),
      backgroundColor: c.inputBackground,
      overflow: 'hidden',
    },
    hpBarFill: {
      height: '100%',
      backgroundColor: c.danger,
      borderRadius: rd(999),
    },

    quickActionsWrapper: {
      backgroundColor: c.card,
      borderRadius: rd(12),
      padding: sp(8),
      borderWidth: 1,
      borderColor: c.border,
      elevation: 2,
    },
    quickActionsDock: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: sp(10),
      paddingTop: sp(6),
      backgroundColor: c.background,
      borderTopWidth: 1,
      borderTopColor: c.border,
      elevation: 8,
    },
    quickActionsRow: {
      gap: sp(8),
      paddingRight: 6,
    },
    quickActionButton: {
      minWidth: 78,
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(8),
      paddingHorizontal: sp(8),
      alignItems: 'center',
      justifyContent: 'center',
      gap: sp(4),
      elevation: 1,
    },
    quickActionText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '700',
      textAlign: 'center',
    },

    tabsWrap: {
      borderRadius: rd(14),
      paddingVertical: sp(6),
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.border,
      elevation: 1,
    },
    tabsRow: {
      gap: sp(8),
      paddingHorizontal: sp(8),
    },
    tabChip: {
      borderRadius: rd(999),
      paddingHorizontal: sp(14),
      paddingVertical: sp(8),
      backgroundColor: c.background,
      borderWidth: 1,
      borderColor: c.border,
    },
    tabChipInner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(4),
    },
    tabChipActive: {
      backgroundColor: c.text,
      borderColor: c.text,
    },
    tabChipConflict: {
      borderColor: c.warning,
    },
    tabChipText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '700',
    },
    tabChipTextActive: {
      color: c.background,
    },

    tabContent: {
      gap: sp(10),
    },
    historyRow: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: sp(9),
      gap: sp(3),
    },
    historyAuthor: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '700',
    },
    historyMeta: {
      color: c.textSecondary,
      fontSize: fs(11),
    },
    historyPaths: {
      color: c.text,
      fontSize: fs(11),
      lineHeight: 16,
    },
    historyShowMoreButton: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(9),
      paddingHorizontal: sp(10),
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    historyShowMoreText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '700',
    },
    cardPrimary: {
      backgroundColor: c.card,
      borderRadius: rd(16),
      padding: sp(12),
      borderWidth: 1,
      borderColor: c.border,
      elevation: 2,
    },
    cardSecondary: {
      backgroundColor: c.card,
      borderRadius: rd(16),
      padding: sp(12),
      borderWidth: 1,
      borderColor: c.border,
      elevation: 2,
      gap: sp(6),
    },
    cardHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: sp(8),
    },
    sectionTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(8),
      flexWrap: 'wrap',
      flex: 1,
    },
    sectionTitle: {
      color: c.text,
      fontSize: fs(15),
      fontWeight: '700',
    },
    sectionConflictBadge: {
      borderRadius: rd(99),
      borderWidth: 1,
      borderColor: c.warning,
      backgroundColor: c.warning,
      paddingVertical: sp(2),
      paddingHorizontal: sp(8),
    },
    sectionConflictBadgeText: {
      color: c.highlight,
      fontSize: fs(10),
      fontWeight: '700',
    },
    subSectionTitle: {
      color: c.text,
      fontSize: fs(13),
      fontWeight: '700',
      marginTop: sp(6),
    },
    collapseButton: {
      borderRadius: rd(8),
      paddingHorizontal: sp(8),
      paddingVertical: sp(6),
      backgroundColor: c.background,
      borderWidth: 1,
      borderColor: c.border,
    },
    collapseButtonText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '600',
    },

    statGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(8),
      marginTop: sp(8),
    },
    statTile: {
      width: '31%',
      minWidth: 92,
      borderRadius: rd(12),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(9),
      paddingHorizontal: sp(10),
      alignItems: 'center',
    },
    statName: {
      color: c.textSecondary,
      fontSize: fs(11),
    },
    statScore: {
      color: c.text,
      fontSize: fs(20),
      fontWeight: '700',
      marginTop: sp(4),
    },
    statMod: {
      color: c.text,
      fontSize: fs(12),
      marginTop: sp(2),
      fontWeight: '600',
    },
    rollHintText: {
      color: c.textSecondary,
      fontSize: fs(10),
      fontWeight: '700',
      marginTop: sp(4),
    },

    rowLine: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      paddingVertical: sp(7),
      gap: sp(8),
    },
    actionRowLine: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      paddingVertical: sp(8),
      gap: sp(8),
      minHeight: 44,
    },
    rowLabel: {
      color: c.text,
      fontSize: fs(13),
      flex: 1,
    },
    rowValue: {
      color: c.text,
      fontSize: fs(13),
      fontWeight: '600',
      maxWidth: '48%',
      textAlign: 'right',
    },
    rankBadge: {
      borderRadius: rd(99),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.inputBackground,
      paddingVertical: sp(3),
      paddingHorizontal: sp(7),
    },
    rankBadgeText: {
      color: c.textSecondary,
      fontSize: fs(10),
      fontWeight: '700',
    },
    rollPill: {
      overflow: 'hidden',
      borderRadius: rd(99),
      backgroundColor: c.primary,
      color: c.onPrimary,
      fontSize: fs(10),
      fontWeight: '800',
      paddingVertical: sp(4),
      paddingHorizontal: sp(8),
    },
    weaponCombatCard: {
      borderRadius: rd(12),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: sp(8),
      gap: sp(8),
    },
    weaponActionRow: {
      flexDirection: 'row',
      gap: sp(8),
    },
    weaponActionButton: {
      flex: 1,
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      paddingVertical: sp(9),
      paddingHorizontal: sp(10),
      alignItems: 'center',
      justifyContent: 'center',
    },
    weaponActionButtonPrimary: {
      backgroundColor: c.info,
      borderColor: c.info,
    },
    weaponActionButtonSecondary: {
      backgroundColor: c.warning,
      borderColor: c.warning,
    },
    weaponActionText: {
      color: c.onPrimary,
      fontSize: fs(12),
      fontWeight: '700',
      textAlign: 'center',
    },
    weaponRollResultLine: {
      color: c.text,
      fontSize: fs(13),
      lineHeight: 18,
    },
    blockText: {
      color: c.text,
      fontSize: fs(13),
      lineHeight: 19,
    },
    blockTextMuted: {
      color: c.textSecondary,
      fontSize: fs(12),
    },
    conditionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: sp(8),
      paddingVertical: sp(3),
    },
    conditionBlock: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingHorizontal: sp(8),
      paddingVertical: sp(6),
      gap: sp(3),
      marginTop: sp(4),
    },
    conditionText: {
      color: c.text,
      fontSize: fs(13),
      flex: 1,
    },
    conditionHint: {
      color: c.textSecondary,
      fontSize: fs(11),
      lineHeight: 16,
      paddingLeft: sp(10),
    },
    sourceFeatureRow: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingHorizontal: sp(8),
      paddingVertical: sp(7),
      gap: sp(4),
      marginTop: sp(4),
    },
    sourceFeatureHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: sp(8),
    },
    sourceFeatureText: {
      color: c.text,
      fontSize: fs(12),
      lineHeight: 18,
      flex: 1,
    },

    trackerCard: {
      borderRadius: rd(12),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: sp(10),
      gap: sp(8),
    },
    trackerHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: sp(8),
    },
    trackerName: {
      color: c.text,
      fontSize: fs(14),
      fontWeight: '700',
    },
    trackerMeta: {
      color: c.textSecondary,
      fontSize: fs(12),
    },
    trackerControls: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: sp(12),
    },
    quickCircle: {
      width: 36,
      height: 36,
      borderRadius: rd(18),
      backgroundColor: c.inputBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickCircleText: {
      color: c.text,
      fontSize: fs(20),
      fontWeight: '700',
      marginTop: -1,
    },
    trackerValue: {
      color: c.text,
      fontSize: fs(18),
      fontWeight: '700',
      minWidth: 78,
      textAlign: 'center',
    },

    editLabel: {
      color: c.textSecondary,
      fontSize: fs(12),
      marginTop: sp(8),
    },
    editInput: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      color: c.text,
      paddingHorizontal: sp(10),
      paddingVertical: sp(9),
      fontSize: fs(14),
    },
    editInputMultiline: {
      minHeight: 92,
      textAlignVertical: 'top',
    },
    numberStepperRow: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: sp(8),
    },
    numberStepperInput: {
      flex: 1,
    },
    numberStepperReadOnlyInput: {
      opacity: 0.9,
    },
    numberStepperControls: {
      width: 44,
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      overflow: 'hidden',
      backgroundColor: c.background,
    },
    numberStepperButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.background,
    },
    numberStepperButtonDisabled: {
      opacity: 0.45,
    },
    numberStepperButtonText: {
      color: c.text,
      fontSize: fs(20),
      fontWeight: '700',
      lineHeight: 22,
    },
    numberStepperButtonTop: {
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    slotEditRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(8),
      marginTop: sp(6),
    },
    slotInput: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      color: c.text,
      paddingHorizontal: sp(10),
      paddingVertical: sp(8),
      width: 72,
      textAlign: 'center',
    },
    secondaryAction: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(9),
      alignItems: 'center',
      marginTop: sp(6),
    },
    secondaryActionText: {
      color: c.text,
      fontSize: fs(13),
      fontWeight: '700',
    },
    editCardBlock: {
      borderRadius: rd(12),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: sp(10),
      marginTop: sp(8),
      gap: sp(4),
    },
    booleanField: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      paddingVertical: sp(10),
      alignItems: 'center',
      marginTop: sp(4),
    },
    removeButton: {
      borderRadius: rd(10),
      backgroundColor: c.danger,
      paddingVertical: sp(8),
      alignItems: 'center',
      marginTop: sp(8),
    },
    removeButtonText: {
      color: c.onPrimary,
      fontSize: fs(12),
      fontWeight: '700',
    },

    modalLabel: {
      color: c.text,
      marginBottom: sp(6),
      marginTop: sp(4),
    },
    modalInput: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      color: c.text,
      paddingHorizontal: sp(10),
      paddingVertical: sp(9),
      marginBottom: sp(8),
    },
    modalInputMultiline: {
      minHeight: 88,
      textAlignVertical: 'top',
    },
    levelModalStatsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(8),
    },
    levelModalStatCell: {
      width: '31%',
      minWidth: 90,
    },
    levelModalInlineInput: {
      flex: 1,
      marginBottom: sp(0),
    },
    levelModalSubmit: {
      marginTop: sp(10),
      marginBottom: sp(18),
    },
    restButton: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(10),
      alignItems: 'center',
      marginBottom: sp(8),
    },
    restButtonText: {
      color: c.text,
      fontWeight: '700',
    },
    diceQuickGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(8),
      marginBottom: sp(8),
    },
    diceQuickChip: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingHorizontal: sp(12),
      paddingVertical: sp(8),
      minWidth: 58,
      alignItems: 'center',
    },
    diceQuickChipActive: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    diceQuickChipText: {
      color: c.text,
      fontSize: fs(13),
      fontWeight: '700',
    },
    diceQuickChipTextActive: {
      color: c.onPrimary,
    },
    diceQuickResultCard: {
      marginTop: sp(8),
      borderRadius: rd(12),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(12),
      paddingHorizontal: sp(10),
      alignItems: 'center',
      gap: sp(4),
    },
    diceQuickResultValue: {
      color: c.text,
      fontSize: fs(28),
      fontWeight: '800',
    },
  });
