import { StyleSheet } from 'react-native';
import { ThemeColors } from '@/shared/styles/theme';

export const getStyles = (c: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.background,
    },
    content: {
      padding: 14,
      paddingBottom: 24,
      gap: 10,
    },
    card: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      padding: 12,
      gap: 8,
      elevation: 1,
    },
    title: {
      color: c.text,
      fontSize: 17,
      fontWeight: '700',
    },
    hint: {
      color: c.textSecondary,
      fontSize: 12,
    },
    statsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    statChip: {
      borderRadius: 99,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 5,
      paddingHorizontal: 10,
    },
    statChipText: {
      color: c.text,
      fontSize: 11,
      fontWeight: '700',
    },
    laneGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    laneButton: {
      width: '48%',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 10,
      paddingHorizontal: 10,
      alignItems: 'center',
      gap: 4,
    },
    laneButtonText: {
      color: c.text,
      fontWeight: '700',
      fontSize: 12,
      textAlign: 'center',
    },
    updateRow: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: 10,
      gap: 2,
    },
    updateTitle: {
      color: c.text,
      fontWeight: '700',
      fontSize: 13,
    },
    updateMeta: {
      color: c.textSecondary,
      fontSize: 12,
    },
    authButton: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 10,
      alignItems: 'center',
      marginTop: 4,
    },
    authButtonText: {
      color: c.text,
      fontWeight: '700',
    },
    topActionButton: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 10,
      paddingHorizontal: 12,
      marginTop: 4,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    topActionButtonText: {
      color: c.text,
      fontWeight: '700',
      fontSize: 12,
    },
    modalLabel: {
      color: c.text,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 4,
      marginBottom: 4,
    },
    modalInput: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 10,
      color: c.text,
      marginBottom: 8,
    },
  });
