import { CharacterDto } from '@/types/Character';

export function createEmptyCharacter(overrides: Partial<CharacterDto> = {}): CharacterDto {
  return {
    id: overrides.id ?? '',
    name: overrides.name ?? '',
    class: overrides.class ?? '',
    subclass: overrides.subclass,
    race: overrides.race ?? '',
    subrace: overrides.subrace,
    background: overrides.background,
    level: overrides.level ?? 1,
    experience: overrides.experience ?? 0,
    initiative: overrides.initiative ?? 0,
    speed: overrides.speed ?? 0,
    ac: overrides.ac ?? 0,
    currency: overrides.currency,
    stats: {
      strength: 10,
      dexterity: 10,
      constitution: 10,
      intelligence: 10,
      wisdom: 10,
      charisma: 10,
      ...(overrides.stats || {}),
    },
    savingThrows: {
      strength: false,
      dexterity: false,
      constitution: false,
      intelligence: false,
      wisdom: false,
      charisma: false,
      ...(overrides.savingThrows || {}),
    },
    skills: {
      acrobatics: 0,
      animalHandling: 0,
      arcana: 0,
      athletics: 0,
      deception: 0,
      history: 0,
      insight: 0,
      intimidation: 0,
      investigation: 0,
      medicine: 0,
      nature: 0,
      perception: 0,
      performance: 0,
      persuasion: 0,
      religion: 0,
      sleightOfHand: 0,
      stealth: 0,
      survival: 0,
      ...(overrides.skills || {}),
    },
    proficiencies: overrides.proficiencies ?? [],
    hp: {
      max: 8,
      current: 8,
      temp: 0,
      ...(overrides.hp || {}),
    },
    hitDice: overrides.hitDice ?? '',
    deathSaves: {
      successes: 0,
      failures: 0,
      ...(overrides.deathSaves || {}),
    },
    inventory: overrides.inventory ?? [],
    armorClassDetails: overrides.armorClassDetails,
    weapons: overrides.weapons ?? [],
    tools: overrides.tools ?? [],
    traits: {
      personality: '',
      ideals: '',
      bonds: '',
      flaws: '',
      ...(overrides.traits || {}),
    },
    featuresAndTraits: overrides.featuresAndTraits ?? [],
    spells: {
      spellcastingAbility: '',
      spellSaveDC: 0,
      spellAttackBonus: 0,
      spellSlots: {},
      knownSpells: [],
      preparedSpells: [],
      cantrips: [],
      ...(overrides.spells || {}),
    },
    notes: overrides.notes,
    alliesAndOrganizations: overrides.alliesAndOrganizations,
    backstory: overrides.backstory,
    campaign: overrides.campaign,
    photoUri: overrides.photoUri,
  };
}
