import type { CharacterDraft, CharacterEntity } from '@/domain/types';
import { parseCharacter } from '@/domain/schemas';

const HIT_DICE_MAP: Record<string, number> = {
  barbarian: 12,
  fighter: 10,
  paladin: 10,
  ranger: 10,
  bard: 8,
  cleric: 8,
  druid: 8,
  monk: 8,
  rogue: 8,
  warlock: 8,
  artificer: 8,
  wizard: 6,
  sorcerer: 6,
};

function getHitDiceSides(className: string): number {
  const key = className.trim().toLowerCase();
  return HIT_DICE_MAP[key] || 6;
}


export function createEmptyCharacter(overrides: CharacterDraft = {}): CharacterEntity {
  const base: CharacterEntity = {
    id: overrides.id ?? '',
    name: overrides.name ?? '',
    class: overrides.class ?? '',
    subclass: overrides.subclass,
    classId: overrides.classId,
    race: overrides.race ?? '',
    subrace: overrides.subrace,
    raceId: overrides.raceId,
    subraceId: overrides.subraceId,
    background: overrides.background,
    backgroundId: overrides.backgroundId,
    contentSources: overrides.contentSources,
    level: overrides.level ?? 1,
    experience: overrides.experience ?? 0,
    initiative: overrides.initiative ?? 0,
    speed: overrides.speed ?? 0,
    ac: overrides.ac ?? 0,
    proficiencyBonus: overrides.proficiencyBonus ?? 2,
    alignment: overrides.alignment,
    currency: overrides.currency,
    characterTemplateId: overrides.characterTemplateId ?? 'standard-5e',
    stats: {
      strength: 10,
      dexterity: 10,
      constitution: 10,
      intelligence: 10,
      wisdom: 10,
      charisma: 10,
      ...(overrides.stats || {}),
    },
    savingThrows: {
      strength: false,
      dexterity: false,
      constitution: false,
      intelligence: false,
      wisdom: false,
      charisma: false,
      ...(overrides.savingThrows || {}),
    },
    skills: {
      acrobatics: 0,
      animalHandling: 0,
      arcana: 0,
      athletics: 0,
      deception: 0,
      history: 0,
      insight: 0,
      intimidation: 0,
      investigation: 0,
      medicine: 0,
      nature: 0,
      perception: 0,
      performance: 0,
      persuasion: 0,
      religion: 0,
      sleightOfHand: 0,
      stealth: 0,
      survival: 0,
      ...(overrides.skills || {}),
    },
    skillProficiencies: overrides.skillProficiencies,
    proficiencies: overrides.proficiencies ?? [],
    hp: {
      max: 8,
      current: 8,
      temp: 0,
      ...(overrides.hp || {}),
    },
    hitDice: overrides.hitDice ?? `${overrides.level ?? 1}d${getHitDiceSides(overrides.class ?? '')}`,
    deathSaves: {
      successes: 0,
      failures: 0,
      ...(overrides.deathSaves || {}),
    },
    inventory: overrides.inventory ?? [],
    armorClassDetails: overrides.armorClassDetails,
    equipment: overrides.equipment,
    weapons: overrides.weapons ?? [],
    tools: overrides.tools ?? [],
    traits: {
      personality: '',
      ideals: '',
      bonds: '',
      flaws: '',
      ...(overrides.traits || {}),
    },
    featuresAndTraits: overrides.featuresAndTraits ?? [],
    spells: {
      spellcastingAbility: '',
      spellSaveDC: 0,
      spellAttackBonus: 0,
      spellSlots: {},
      knownSpells: [],
      preparedSpells: [],
      cantrips: [],
      ...(overrides.spells || {}),
    },
    notes: overrides.notes,
    alliesAndOrganizations: overrides.alliesAndOrganizations,
    backstory: overrides.backstory,
    campaign: overrides.campaign,
    campaignId: overrides.campaignId,
    photoUri: overrides.photoUri,
    sessionMode: overrides.sessionMode ?? false,
    conditions: overrides.conditions ?? [],
    customFields: overrides.customFields ?? [],
    customTrackers: overrides.customTrackers ?? [],
    customSections: overrides.customSections ?? [],
    customResources: overrides.customResources ?? [],
    customResetRules: overrides.customResetRules ?? [],
    customFeatureBlocks: overrides.customFeatureBlocks ?? [],
    customSpellLists: overrides.customSpellLists ?? [],
    customNotesGroups: overrides.customNotesGroups ?? [],
    homebrewEntries: overrides.homebrewEntries ?? [],
    notesBlocks: {
      session: '',
      campaign: '',
      goals: '',
      relationships: '',
      quests: '',
      ...(overrides.notesBlocks || {}),
    },
    combatTemplates: {
      actions: [],
      bonusActions: [],
      reactions: [],
      ...(overrides.combatTemplates || {}),
    },
  };

  return parseCharacter(base);
}
