import { StyleSheet } from 'react-native';
import type { ThemeColors } from '@/shared/styles/theme';
import { fs, rd, sp } from '@/shared/styles/tokens';

export const getStyles = (c: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.background,
      paddingHorizontal: sp(14),
      paddingTop: 14,
      gap: sp(10),
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: sp(10),
    },
    headerMeta: {
      flex: 1,
      gap: sp(4),
    },
    headerAction: {
      borderRadius: rd(10),
      backgroundColor: c.primary,
      paddingHorizontal: sp(12),
      paddingVertical: sp(9),
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(5),
      marginTop: sp(2),
    },
    headerActionText: {
      color: c.onPrimary,
      fontSize: fs(12),
      fontWeight: '700',
    },
    title: {
      color: c.text,
      fontSize: fs(21),
      fontWeight: '700',
    },
    hint: {
      color: c.textSecondary,
      fontSize: fs(13),
      lineHeight: 18,
    },
    offlineBanner: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.info,
      backgroundColor: c.info,
      paddingHorizontal: sp(10),
      paddingVertical: sp(8),
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(8),
    },
    offlineBannerText: {
      color: c.onInfo,
      fontSize: fs(12),
      lineHeight: 17,
      flex: 1,
    },
    search: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      color: c.text,
      paddingHorizontal: sp(10),
      paddingVertical: sp(8),
    },
    filtersBlock: {
      gap: sp(6),
    },
    tabsRow: {
      gap: sp(8),
      paddingVertical: sp(2),
    },
    tabButton: {
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      paddingHorizontal: sp(12),
      paddingVertical: sp(8),
      minWidth: sp(72),
      alignItems: 'center',
    },
    tabButtonActive: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    tabButtonText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '700',
    },
    tabButtonTextActive: {
      color: c.onPrimary,
    },
    chipsRow: {
      gap: sp(8),
      paddingVertical: sp(2),
    },
    chip: {
      borderRadius: rd(999),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      paddingHorizontal: sp(10),
      paddingVertical: sp(7),
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(6),
    },
    chipActive: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    chipText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '600',
    },
    chipTextActive: {
      color: c.onPrimary,
    },
    activeFiltersRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: sp(8),
    },
    clearButton: {
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      paddingHorizontal: sp(10),
      paddingVertical: sp(6),
    },
    clearButtonText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '700',
    },
    characterPickerBlock: {
      gap: sp(6),
    },
    sectionLabel: {
      color: c.textSecondary,
      fontSize: fs(12),
      fontWeight: '600',
    },
    listContent: {
      paddingBottom: 24,
      gap: sp(8),
    },
    card: {
      borderRadius: rd(12),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      padding: sp(10),
      gap: sp(8),
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: sp(8),
    },
    cardHeaderMain: {
      flex: 1,
      gap: sp(2),
    },
    favoriteButton: {
      borderRadius: rd(14),
      padding: sp(4),
    },
    spellName: {
      color: c.text,
      fontSize: fs(15),
      fontWeight: '700',
    },
    meta: {
      color: c.textSecondary,
      fontSize: fs(12),
    },
    description: {
      color: c.text,
      fontSize: fs(13),
      lineHeight: 18,
    },
    metadataGrid: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingHorizontal: sp(8),
      paddingVertical: sp(7),
      gap: sp(3),
    },
    metadataText: {
      color: c.text,
      fontSize: fs(12),
      lineHeight: 17,
    },
    tagRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(6),
    },
    smallTag: {
      borderRadius: rd(999),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingHorizontal: sp(8),
      paddingVertical: sp(5),
    },
    smallTagActive: {
      borderColor: c.success,
      backgroundColor: c.success,
    },
    smallTagText: {
      color: c.text,
      fontSize: fs(11),
      fontWeight: '700',
    },
    smallTagTextActive: {
      color: c.onPrimary,
    },
    sourceBadge: {
      borderRadius: rd(999),
      borderWidth: 1,
      borderColor: c.info,
      backgroundColor: c.info,
      paddingHorizontal: sp(8),
      paddingVertical: sp(5),
    },
    sourceBadgeText: {
      color: c.onInfo,
      fontSize: fs(11),
      fontWeight: '700',
    },
    damageBlock: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingHorizontal: sp(8),
      paddingVertical: sp(7),
      gap: sp(2),
    },
    damageLine: {
      color: c.text,
      fontSize: fs(12),
      lineHeight: 17,
    },
    statusLine: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    statusText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '600',
    },
    statusButtonsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(6),
    },
    toggleRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(8),
      marginTop: sp(4),
    },
    statusButton: {
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingHorizontal: sp(8),
      paddingVertical: sp(6),
    },
    statusButtonActive: {
      backgroundColor: c.success,
      borderColor: c.success,
    },
    statusButtonText: {
      color: c.text,
      fontSize: fs(11),
      fontWeight: '700',
    },
    statusButtonTextActive: {
      color: c.onPrimary,
    },
    metaMuted: {
      color: c.textSecondary,
      fontSize: fs(12),
    },
    preparedInfo: {
      color: c.textSecondary,
      fontSize: fs(12),
      marginTop: sp(4),
    },
    preparedWarning: {
      color: c.warning,
      fontSize: fs(12),
      marginTop: sp(4),
      fontWeight: '600',
    },
    cardActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(8),
      marginTop: sp(2),
    },
    cardActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(6),
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingHorizontal: sp(10),
      paddingVertical: sp(7),
      flex: 1,
    },
    cardActionText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '600',
    },
    deleteCustomButton: {
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.danger,
      backgroundColor: c.danger,
      paddingVertical: sp(7),
      paddingHorizontal: sp(12),
      alignItems: 'center',
    },
    deleteCustomButtonText: {
      color: c.onPrimary,
      fontSize: fs(12),
      fontWeight: '700',
    },
    empty: {
      color: c.textSecondary,
      fontSize: fs(13),
      marginTop: sp(6),
      marginBottom: sp(14),
    },
    errorText: {
      color: c.danger,
      fontSize: fs(13),
      fontWeight: '700',
      marginTop: sp(6),
      marginBottom: sp(14),
    },
    modalScroll: {
      flex: 1,
      minHeight: 0,
    },
    modalScrollContent: {
      paddingBottom: 12,
      gap: sp(6),
    },
    modalLabel: {
      color: c.textSecondary,
      fontSize: fs(12),
      marginTop: sp(4),
    },
    modalInput: {
      borderRadius: rd(10),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      color: c.text,
      paddingHorizontal: sp(10),
      paddingVertical: sp(8),
      fontSize: fs(14),
    },
    modalInputMultiline: {
      minHeight: 80,
      textAlignVertical: 'top',
    },
    modalInputLarge: {
      minHeight: 120,
      textAlignVertical: 'top',
    },
    modalHint: {
      color: c.textSecondary,
      fontSize: fs(11),
      lineHeight: 16,
    },
  });



