import { StyleSheet } from 'react-native';
import { ThemeColors } from '@/shared/styles/theme';

export const getStyles = (c: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.background,
    },
    content: {
      padding: 16,
      paddingBottom: 36,
      gap: 10,
    },
    progressRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    progressText: {
      color: c.textSecondary,
      fontSize: 12,
      fontWeight: '600',
    },
    title: {
      color: c.text,
      fontSize: 22,
      fontWeight: '700',
    },
    card: {
      backgroundColor: c.card,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      padding: 12,
      gap: 8,
      elevation: 2,
    },
    sectionTitle: {
      color: c.text,
      fontSize: 18,
      fontWeight: '700',
    },
    sectionHint: {
      color: c.textSecondary,
      fontSize: 13,
    },
    label: {
      color: c.text,
      marginTop: 8,
      fontSize: 15,
      fontWeight: '600',
    },
    input: {
      backgroundColor: c.background,
      color: c.text,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      marginTop: 4,
    },
    picker: {
      backgroundColor: c.background,
      color: c.text,
      marginTop: 4,
      borderRadius: 10,
      height: 50,
    },
    toggleRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 8,
    },
    toggleButton: {
      flex: 1,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    toggleButtonActive: {
      backgroundColor: c.text,
      borderColor: c.text,
    },
    toggleButtonText: {
      color: c.text,
      fontSize: 13,
      fontWeight: '700',
      textAlign: 'center',
    },
    toggleButtonTextActive: {
      color: c.background,
    },
    methodCard: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: 12,
      gap: 6,
    },
    methodCardActive: {
      borderColor: c.text,
      backgroundColor: c.inputBackground,
    },
    methodTitle: {
      color: c.text,
      fontSize: 15,
      fontWeight: '700',
    },
    methodMeta: {
      color: c.textSecondary,
      fontSize: 13,
    },
    statRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 8,
      gap: 8,
    },
    statLabel: {
      color: c.text,
      fontSize: 14,
      fontWeight: '600',
      width: 130,
    },
    statControl: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 6,
      paddingHorizontal: 10,
      minWidth: 36,
      alignItems: 'center',
    },
    statControlText: {
      color: c.text,
      fontWeight: '700',
    },
    statValue: {
      color: c.text,
      minWidth: 32,
      textAlign: 'center',
      fontWeight: '700',
      fontSize: 15,
    },
    helperText: {
      color: c.textSecondary,
      fontSize: 12,
      marginTop: 6,
    },
    warningText: {
      color: c.danger,
      fontSize: 12,
      marginTop: 6,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      paddingVertical: 6,
    },
    summaryLabel: {
      color: c.textSecondary,
      fontSize: 13,
      flex: 1,
    },
    summaryValue: {
      color: c.text,
      fontSize: 13,
      flex: 1,
      textAlign: 'right',
      fontWeight: '600',
    },
    infoBox: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: 10,
      marginTop: 6,
      gap: 4,
    },
    navRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 10,
    },
    navButton: {
      flex: 1,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      paddingVertical: 12,
      alignItems: 'center',
    },
    navButtonPrimary: {
      backgroundColor: c.text,
      borderColor: c.text,
    },
    navButtonDisabled: {
      opacity: 0.45,
    },
    navButtonText: {
      color: c.text,
      fontWeight: '700',
      fontSize: 14,
    },
    navButtonTextPrimary: {
      color: c.background,
    },
    chipsWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 6,
    },
    chip: {
      borderRadius: 99,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    chipText: {
      color: c.text,
      fontSize: 11,
      fontWeight: '600',
    },
  });

