import { StyleSheet } from 'react-native';
import type { ThemeColors } from '@/shared/styles/theme';
import { fs, rd, sp } from '@/shared/styles/tokens';

export const getStyles = (c: ThemeColors) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: c.background,
    },
    shell: {
      flex: 1,
      backgroundColor: c.background,
    },
    header: {
      paddingHorizontal: sp(16),
      paddingTop: sp(10),
      paddingBottom: sp(8),
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      backgroundColor: c.background,
      gap: sp(6),
    },
    scroll: {
      flex: 1,
      backgroundColor: c.background,
    },
    content: {
      padding: sp(16),
      gap: sp(12),
    },
    loadingState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    progressRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: sp(10),
    },
    progressText: {
      color: c.textSecondary,
      fontSize: fs(12),
      fontWeight: '700',
    },
    title: {
      color: c.text,
      fontSize: fs(22),
      fontWeight: '800',
    },
    draftBanner: {
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      borderRadius: rd(8),
      padding: sp(8),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: sp(8),
    },
    inlineAction: {
      borderRadius: rd(8),
      paddingHorizontal: sp(8),
      paddingVertical: sp(6),
      backgroundColor: c.inputBackground,
    },
    inlineActionText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '700',
    },
    card: {
      backgroundColor: c.card,
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      padding: sp(12),
      gap: sp(8),
      elevation: 2,
    },
    sectionTitle: {
      color: c.text,
      fontSize: fs(18),
      fontWeight: '800',
    },
    sectionHint: {
      color: c.textSecondary,
      fontSize: fs(13),
      lineHeight: fs(18),
    },
    label: {
      color: c.text,
      marginTop: sp(6),
      fontSize: fs(14),
      fontWeight: '700',
    },
    input: {
      backgroundColor: c.background,
      color: c.text,
      paddingHorizontal: sp(12),
      paddingVertical: sp(10),
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      minHeight: 44,
    },
    multilineInput: {
      minHeight: 84,
      textAlignVertical: 'top',
    },
    largeInput: {
      minHeight: 132,
      textAlignVertical: 'top',
    },
    picker: {
      backgroundColor: c.background,
      color: c.text,
      borderRadius: rd(8),
      minHeight: 50,
    },
    portraitRow: {
      flexDirection: 'row',
      gap: sp(12),
      alignItems: 'center',
    },
    portrait: {
      width: 84,
      height: 84,
      borderRadius: rd(8),
      backgroundColor: c.inputBackground,
    },
    portraitPlaceholder: {
      width: 84,
      height: 84,
      borderRadius: rd(8),
      backgroundColor: c.inputBackground,
      borderWidth: 1,
      borderColor: c.border,
    },
    portraitActions: {
      flex: 1,
      gap: sp(8),
    },
    methodCard: {
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: sp(12),
      gap: sp(5),
      minHeight: 68,
    },
    methodCardActive: {
      borderColor: c.primary,
      backgroundColor: c.inputBackground,
    },
    methodTitle: {
      color: c.text,
      fontSize: fs(15),
      fontWeight: '800',
    },
    methodMeta: {
      color: c.textSecondary,
      fontSize: fs(13),
      lineHeight: fs(18),
    },
    toggleRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(8),
      marginTop: sp(4),
    },
    toggleButton: {
      flexGrow: 1,
      flexBasis: 96,
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(11),
      paddingHorizontal: sp(8),
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 44,
    },
    toggleButtonActive: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    toggleButtonText: {
      color: c.text,
      fontSize: fs(13),
      fontWeight: '800',
      textAlign: 'center',
    },
    toggleButtonTextActive: {
      color: c.onPrimary,
    },
    statRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: sp(10),
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      paddingVertical: sp(7),
    },
    statLabelBlock: {
      flex: 1,
    },
    statLabel: {
      color: c.text,
      fontSize: fs(14),
      fontWeight: '800',
    },
    stepper: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: sp(8),
    },
    statControl: {
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statControlText: {
      color: c.text,
      fontSize: fs(18),
      fontWeight: '800',
    },
    statValue: {
      color: c.text,
      minWidth: 38,
      textAlign: 'center',
      fontWeight: '800',
      fontSize: fs(15),
    },
    statInput: {
      width: 76,
      textAlign: 'center',
    },
    rollControl: {
      flex: 1,
      minWidth: 150,
      alignItems: 'flex-end',
      gap: sp(6),
    },
    helperText: {
      color: c.textSecondary,
      fontSize: fs(12),
      lineHeight: fs(17),
    },
    statRowFullWidthHint: {
      width: '100%',
    },
    arrayChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(6),
    },
    arrayChip: {
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(6),
      paddingHorizontal: sp(10),
    },
    arrayChipActive: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    arrayChipText: {
      color: c.text,
      fontWeight: '800',
      fontSize: fs(13),
    },
    arrayChipTextActive: {
      color: c.onPrimary,
    },
    warningText: {
      color: c.danger,
      fontSize: fs(12),
      lineHeight: fs(17),
      fontWeight: '700',
    },
    infoBox: {
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      padding: sp(10),
      gap: sp(4),
    },
    chipsWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: sp(7),
      marginTop: sp(4),
    },
    chip: {
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(8),
      paddingHorizontal: sp(10),
      minHeight: 40,
      justifyContent: 'center',
    },
    chipActive: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    chipText: {
      color: c.text,
      fontSize: fs(12),
      fontWeight: '800',
    },
    chipTextActive: {
      color: c.onPrimary,
    },
    threeColumnRow: {
      flexDirection: 'row',
      gap: sp(8),
    },
    column: {
      flex: 1,
    },
    smallButton: {
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.background,
      paddingVertical: sp(10),
      paddingHorizontal: sp(12),
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 44,
    },
    smallButtonText: {
      color: c.text,
      fontWeight: '800',
      fontSize: fs(13),
    },
    reviewName: {
      color: c.text,
      fontSize: fs(22),
      fontWeight: '900',
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: sp(12),
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      paddingVertical: sp(8),
    },
    summaryLabel: {
      color: c.textSecondary,
      fontSize: fs(13),
      flex: 1,
    },
    summaryValue: {
      color: c.text,
      fontSize: fs(13),
      flex: 1,
      textAlign: 'right',
      fontWeight: '800',
    },
    footer: {
      flexDirection: 'row',
      gap: sp(10),
      paddingHorizontal: sp(16),
      paddingTop: sp(10),
      paddingBottom: sp(16),
      borderTopWidth: 1,
      borderTopColor: c.border,
      backgroundColor: c.background,
    },
    navButton: {
      flex: 1,
      borderRadius: rd(8),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      paddingVertical: sp(12),
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 48,
    },
    navButtonPrimary: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    navButtonDisabled: {
      opacity: 0.45,
    },
    navButtonText: {
      color: c.text,
      fontWeight: '800',
      fontSize: fs(14),
    },
    navButtonTextPrimary: {
      color: c.onPrimary,
    },
  });
