
export const SUBCLASSES: Record<string, string[]> = {
  barbarian: [
    'Path of the Berserker',
    'Path of the Totem Warrior',
    'Path of the Zealot',
    'Path of the Ancestral Guardian',
  ],
  fighter: [
    'Champion',
    'Battle Master',
    'Eldritch Knight',
    'Arcane Archer',
    'Cavalier',
    'Samurai',
  ],
  paladin: [
    'Oath of Devotion',
    'Oath of the Ancients',
    'Oath of Vengeance',
    'Oathbreaker',
  ],
  ranger: [
    'Hunter',
    'Beast Master',
    'Gloom Stalker',
    'Horizon Walker',
    'Monster Slayer',
  ],
  bard: [
    'College of Lore',
    'College of Valor',
    'College of Swords',
    'College of Glamour',
    'College of Whispers',
  ],
  cleric: [
    'Life Domain',
    'Light Domain',
    'War Domain',
    'Tempest Domain',
    'Knowledge Domain',
    'Trickery Domain',
    'Forge Domain',
    'Grave Domain',
  ],
  druid: [
    'Circle of the Land',
    'Circle of the Moon',
    'Circle of Dreams',
    'Circle of the Shepherd',
    'Circle of Spores',
  ],
  monk: [
    'Way of the Open Hand',
    'Way of Shadow',
    'Way of the Four Elements',
    'Way of the Kensei',
    'Way of the Drunken Master',
  ],
  rogue: [
    'Thief',
    'Assassin',
    'Arcane Trickster',
    'Inquisitive',
    'Mastermind',
    'Scout',
    'Swashbuckler',
  ],
  warlock: [
    'The Archfey',
    'The Fiend',
    'The Great Old One',
    'The Hexblade',
    'The Celestial',
  ],
  artificer: [
    'Alchemist',
    'Armorer',
    'Artillerist',
    'Battle Smith',
  ],
  wizard: [
    'School of Abjuration',
    'School of Conjuration',
    'School of Divination',
    'School of Enchantment',
    'School of Evocation',
    'School of Illusion',
    'School of Necromancy',
    'School of Transmutation',
    'Bladesinging',
  ],
  sorcerer: [
    'Draconic Bloodline',
    'Wild Magic',
    'Divine Soul',
    'Shadow Magic',
    'Storm Sorcery',
    'Aberrant Mind',
    'Clockwork Soul',
  ],
  custom: [], // subclasses are free-text for custom classes
};
